### ISSUE TITLE
Error talking to Switchbot 

### ISSUE THREAD

**Issue by arthur-morgan-1** [cagnulein/switchbot_press#9]
Hey,
I'm having the same problem through the official integration, I thought this custom component may solve it, but it's still the same, maybe you have an idea?

The bluetooth works fine because the device is found both on the official integration and on switchbot_press.
But when I try to toggle the switch, nothing happens and I get this errors on logs:

```
Cannot connect to Switchbot. Retrying (remaining: 3)...
02:38:07 – (WARNING) /usr/local/lib/python3.9/site-packages/switchbot/__init__.py
Error talking to Switchbot.
02:38:07 – (WARNING) /usr/local/lib/python3.9/site-packages/switchbot/__init__.py
```

**Comment by cagnulein** [comment]
Does it work with its own app?

**Comment by arthur-morgan-1** [comment]
> Does it work with its own app?

Yes, it does

**Comment by cagnulein** [comment]
where hass is running?

**Comment by arthur-morgan-1** [comment]
> where hass is running?

Intel NUC with TP bluetooth dongle. The dongle works for sure because it finds the device automatically from the official integration. Also shows the battery status from there.

**Comment by cagnulein** [comment]
The fact that it gets the advertising frame doesn't mean that it able to connect to it
Since you are the only one with this issue I will try with a different dongle

**Comment by nthulke** [comment]
I am getting this error, I moved my install from Servercore (Pi4) to a Hassio on a Pi4 and ever since the migration I get this in the logs.

```
2022-04-04 18:05:15 WARNING (SyncWorker_2) [switchbot] Error talking to Switchbot.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/switchbot/__init__.py", line 92, in _sendcommand
    self._connect()
  File "/usr/local/lib/python3.9/site-packages/switchbot/__init__.py", line 45, in _connect
    self._device = bluepy.btle.Peripheral(self._mac,
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral EA:10:5B:B9:52:14, addr type: random
2022-04-04 18:05:15 WARNING (SyncWorker_2) [switchbot] Cannot connect to Switchbot. Retrying (remaining: 3)...
2022-04-04 18:05:19 WARNING (MainThread) [homeassistant.components.switch] Updating switchbot_press switch took longer than the scheduled update interval 0:00:30
2022-04-04 18:05:49 WARNING (MainThread) [homeassistant.components.switch] Updating switchbot_press switch took longer than the scheduled update interval 0:00:30
2022-04-04 18:05:56 WARNING (SyncWorker_2) [switchbot] Error talking to Switchbot.
```

If I switch back to my old install it works so not sure what is going on.

EDIT: Ok I have sorted the issue, That error is cannot see the BT switch, if I move it closer (inside 2m) it can connect and activate it as normal. Turns out the heatsink case I put the new PI4 in dampers the range of BT. Hope this might be able to help others. I was able to run SSH on my install and run "bluetoothctl" then run "scan on" then I was able to see the Switchbot in the list

![Screenshot 2022-04-04 183039](https://user-images.githubusercontent.com/69140718/161505172-3281bc0b-95fa-4581-b448-b5f48ac5a406.png)
.

**Comment by cagnulein** [comment]
@nthulke thanks for the feedback!
